name: 'data_platform'
version: '1.0.0'
profile: 'data_platform' # This should match the profile name in your profiles.yml file


model-paths: ["models"] # 
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:    
  - "target"
  - "dbt_packages"


models:
  data_platform:
    staging:
      +materialized: table
    intermediate: 
      +materialized: table
    marts:
      +materialized: table