services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:16
    container_name: postgres_kestra
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    user: root
    ports:
      - "8080:8080"
    command: server standalone --flow-path /app/flows
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KESTRA_CONFIGURATION: |
        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /app/flows
        datasources:
          postgres:
            url: jdbc:postgresql://postgres_kestra:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          tutorial-flows:
            enabled: false
          server:
            type: embedded
          queue:
            type: postgres
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: /app/storage
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true
      ENV_ALPHA_VANTAGE_API_KEY: "${ALPHA_VANTAGE_API_KEY}"
      ENV_MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      ENV_MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      ENV_PROJECT_PATH: "${PROJECT_PATH}"
    env_file:
      - ../.env
    volumes:
      - kestra_data:/app/storage
      - ./flows:/app/flows
      - /var/run/docker.sock:/var/run/docker.sock

  superset:
    image: superset-custom:latest
    container_name: superset
    ports:
      - "8088:8088"
    volumes:
      - superset_data:/app/superset_home
      - /Users/jacodon/Dev/data-platform/warehouse:/warehouse
    environment:
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
    restart: unless-stopped

volumes:
  minio_data:
  postgres_data:
  kestra_data:
  superset_data: