services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
    # Access to the MinIO API
      - "9000:9000"
    # Access to the MinIO Console
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
    # Mount the volume for MinIO data storage
      - minio_data:/data

  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    user: root
    ports:
    # Access to the Kestra Console
      - "8080:8080"
    command: server standalone
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          server:
            type: embedded
          queue:
            type: memory
          repository:
            type: memory
          storage:
            type: local
            local:
              base-path: /app/storage
      ENV_ALPHA_VANTAGE_API_KEY: "${ALPHA_VANTAGE_API_KEY}"
      ENV_MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      ENV_MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"  
      ENV_PROJECT_PATH: "${PROJECT_PATH}"
    env_file:
      - ../.env
    volumes:
      # Mount the volume for Kestra data storage
      - kestra_data:/app/storage
      # Mount the bind mount for Kestra flows
      - ./flows:/app/flows
      # Mount the Docker socket to allow Kestra to interact with Docker
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  minio_data:
  kestra_data: